"""baseline

Revision ID: 9a15d72f1d44
Revises:
Create Date: 2026-04-20 01:31:16.987496

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "9a15d72f1d44"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
