"""content module tables

Revision ID: 9bb788c7d177
Revises: a5d3c8e91f02
Create Date: 2026-04-23 12:14:15.336761

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9bb788c7d177"
down_revision: str | None = "a5d3c8e91f02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pieces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("cefr", sa.String(length=2), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("topic", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("generation_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("cefr IN ('A1','A2','B1','B2','C1')", name="pieces_cefr_chk"),
        sa.CheckConstraint("kind IN ('reading','listening','speaking','writing')", name="pieces_kind_chk"),
        sa.CheckConstraint("source IN ('editorial','llm_generated')", name="pieces_source_chk"),
        sa.CheckConstraint("status IN ('draft','published','archived')", name="pieces_status_chk"),
        sa.CheckConstraint("minutes BETWEEN 1 AND 60", name="pieces_minutes_chk"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index("pieces_created_at_idx", "pieces", ["created_at", "id"], unique=False)
    op.create_index("pieces_library_idx", "pieces", ["status", "kind", "cefr", "topic"], unique=False)
    op.create_table(
        "content_generation_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("admin_user_id", sa.UUID(), nullable=False),
        sa.Column("piece_id", sa.UUID(), nullable=True),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_hash", sa.String(length=128), nullable=False),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('succeeded','failed')", name="cg_log_status_chk"),
        sa.ForeignKeyConstraint(
            ["admin_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["piece_id"], ["pieces.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "listening_pieces",
        sa.Column("piece_id", sa.UUID(), nullable=False),
        sa.Column("audio_storage_key", sa.String(length=512), nullable=True),
        sa.Column("audio_mime", sa.String(length=64), nullable=True),
        sa.Column("audio_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column("mcq", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("short_answer", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["piece_id"], ["pieces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("piece_id"),
    )
    op.create_table(
        "reading_pieces",
        sa.Column("piece_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("mcq", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("short_answer", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["piece_id"], ["pieces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("piece_id"),
    )
    op.create_table(
        "speaking_pieces",
        sa.Column("piece_id", sa.UUID(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("reference_audio_storage_key", sa.String(length=512), nullable=True),
        sa.Column("reference_audio_mime", sa.String(length=64), nullable=True),
        sa.Column("reference_audio_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("rubric", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["piece_id"], ["pieces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("piece_id"),
    )
    op.create_table(
        "writing_pieces",
        sa.Column("piece_id", sa.UUID(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("exemplar", sa.Text(), nullable=True),
        sa.Column("rubric", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["piece_id"], ["pieces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("piece_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # content_generation_log first (depends on pieces + users)
    op.drop_table("content_generation_log")
    # four kind subtables next (each depends only on pieces)
    op.drop_table("writing_pieces")
    op.drop_table("speaking_pieces")
    op.drop_table("reading_pieces")
    op.drop_table("listening_pieces")
    # pieces last
    op.drop_index("pieces_library_idx", table_name="pieces")
    op.drop_index("pieces_created_at_idx", table_name="pieces")
    op.drop_table("pieces")
    # ### end Alembic commands ###
